name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours (at minute 0 of hour 0, 6, 12, 18 UTC)
  workflow_dispatch:  # 👈 Add this line

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]  # Add/remove versions as needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      working-directory: ./newch

    - name: Run tests
      run: npm start
      working-directory: ./newch

    - name: Build (if needed)
      run: npm run build
      working-directory: ./newch
      # Remove or modify this if you don’t have a build script
